"""
embed_pack.py - inlines a pack into the app for a published build.

WHY THIS EXISTS
  On a field device the instrument loads the pack from the device store, or imports a pack file
  handed over by another team. A PUBLISHED build (a web page a judge opens, or a single page sent
  to somebody) has no packs folder to fetch from, and may run in a sandbox that blocks fetches
  altogether. So the pack is written into a script the page loads directly.

  The instrument labels this case "embedded in this page", because a demonstration copy is not the
  same thing as a pack a responder downloaded and can hand on. Nothing is hidden by doing it: the
  layers, the provenance and the limitations are exactly the ones the pipeline produced.

HOW TO RUN
  python embed_pack.py            writes ../app/pack-embed.js
  The local build does not need it; delete that file to go back to downloading packs.
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
INGITO = HERE.parent
PACKS = INGITO / "packs"
OUT = INGITO / "app" / "pack-embed.js"


def main():
    found = sorted(PACKS.glob("*.pack.json"))
    if not found:
        raise SystemExit(f"No pack in {PACKS}. Run build_pack.py first.")
    pack = json.loads(found[-1].read_text(encoding="utf-8"))
    OUT.write_text(
        "/* Generated by pipeline/embed_pack.py. One disaster pack, inlined for a published build. */\n"
        "window.INGITO_PACK = " + json.dumps(pack, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print(f"wrote app/{OUT.name} ({OUT.stat().st_size / 1024 / 1024:.1f} MB)")
    print(f"  pack        {pack['pack_id']} - {pack['name']}")
    print(f"  hazard      {pack['observation']['sensor']} {pack['observation']['acquisition_date']}, "
          f"{pack['observation']['totals']['flood_km2']} km2, "
          f"{pack['observation']['feature_count']} patches")
    print(f"  context     {len(pack['context']['roads'])} roads, "
          f"{len(pack['context']['waterways'])} waterways, "
          f"{len(pack['context']['shelters'])} shelters")


if __name__ == "__main__":
    main()
