"""
embed_pack.py - writes app/pack-embed.js, a copy of the region pack inlined into one script.

Why this exists: the published (Artifact) build runs in a sandbox that may refuse both service
workers and same-origin fetches, so the downloadable pack cannot be relied on there. The app
falls back to this embedded copy and labels it "embedded in this page", so nobody mistakes the
published demo for the real offline install.

The local build does not need this file.

Run:   ..\\sar-flood\\run.cmd pack\\embed_pack.py        (from the guidebook folder)
"""

import base64
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
GUIDEBOOK = HERE.parent
PACK = GUIDEBOOK / "packs" / "chattogram-south"
OUT = GUIDEBOOK / "app" / "pack-embed.js"


def main():
    manifest = json.loads((PACK / "manifest.json").read_text(encoding="utf-8"))
    bundle = {
        "manifest": manifest,
        "region": json.loads((PACK / "region.geojson").read_text(encoding="utf-8")),
        "terrain": "data:image/png;base64,"
                   + base64.b64encode((PACK / "terrain.png").read_bytes()).decode("ascii"),
    }
    change = PACK / "change.geojson"
    if change.exists():
        bundle["change"] = json.loads(change.read_text(encoding="utf-8"))

    OUT.write_text(
        "/* Generated by pack/embed_pack.py. The region pack, inlined for the published build. */\n"
        "window.GUIDEBOOK_PACK = " + json.dumps(bundle, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print(f"wrote app/{OUT.name} ({OUT.stat().st_size / 1024:.0f} KB)")
    print(f"  embedded: {', '.join(key for key in bundle if key != 'manifest')}")
    for layer in manifest["layers"]:
        print(f"  {layer['status'].split(':')[0]:8s} {layer['id']}")


if __name__ == "__main__":
    main()
